app1/urls.py
from django.urls import path
from app1.views import *
app_name='bunny'

urlpatterns=[
    path('allu/',allu,name='allu'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='laddu'

urlpatterns=[
    path('chandhu/',chandhu,name='chandhu'),
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
from app2.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('prabha/',prabha,name='prabha'),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def allu(request):
    return render(request,'allu.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def prabha(request):
    return render(request,'prabha.html')

templates/allu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hii</h1>
        <h1><a href="{% url 'prabha' %}">dailogue on prabha</a></h1>
    </center>
</body>
</html>

templates/prabha.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            hii maa
        </h1>
        <h1>
            <a href="{% url 'bunny:allu' %}">dailogue on allu</a>
        </h1>
    </center>
</body>
</html>